import React from 'react';
import './About.css'

const About = () => {
    return (
        <div className='about-container'>
            <h1>About our amazing journey</h1>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Maiores eligendi unde natus harum cupiditate dicta, vero, quidem aperiam laborum rem inventore placeat. Iure hic eligendi vitae eius ut officiis assumenda illum, excepturi perferendis quidem delectus officia, sunt adipisci atque voluptatem. Ipsum labore obcaecati nihil dolorum incidunt, dolores repudiandae libero. Quo iste minima, assumenda impedit autem dolore porro vel neque, quaerat odio sint similique illum hic, earum atque ipsa modi aliquid laboriosam sed odit? Harum fugit ad ipsum maiores consequuntur, non at pariatur optio eos temporibus recusandae labore porro unde quas rem illo corporis dolore nesciunt, dolorum tenetur maxime in ab asperiores. Minus nemo quo nobis nihil natus ad, possimus doloribus vitae itaque excepturi repudiandae nostrum adipisci nisi quaerat error mollitia voluptatem ut ratione optio pariatur eveniet inventore? Odio dicta officia hic aperiam at corrupti soluta, officiis voluptatibus deleniti nihil quae error cupiditate quo fuga omnis impedit praesentium mollitia! Ipsa nulla harum laborum expedita suscipit corrupti rem quaerat libero voluptates! Enim nesciunt vitae incidunt tempore consequuntur placeat! Distinctio, quo ratione quia, laborum placeat sequi atque temporibus numquam similique aut accusamus nisi deserunt velit. Ipsa nostrum deleniti nihil ea architecto deserunt? Suscipit molestiae hic et officiis enim numquam, non </p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum, at cupiditate dolores explicabo praesentium quaerat esse fugiat molestias soluta exercitationem, maxime itaque nam illum nostrum eum corrupti repellat officiis vitae laudantium. Eum cum amet praesentium! Dolor distinctio est facere quibusdam ex velit tenetur architecto id sit, ad vitae laudantium iste eveniet quo quas nostrum fuga voluptate. Suscipit maxime non harum eveniet necessitatibus ratione dolor nostrum fuga placeat. Laborum doloribus neque aut obcaecati eos rerum et nemo itaque sint eius asperiores saepe, perspiciatis laboriosam mollitia enim. Aliquam, quis quisquam? Vitae, ab delectus? Nesciunt nostrum error iste impedit. Provident doloremque autem ullam aperiam velit inventore a laboriosam minus quod in, consequuntur facere repellendus neque qui eligendi! Aliquid, iure aperiam provident delectus dolores, quisquam explicabo culpa, deserunt ducimus libero possimus cum in quaerat laborum consectetur non aliquam tenetur vero fugiat asperiores numquam. Modi labore iste tempora eligendi, dolore, laudantium ut minima quibusdam laborum voluptatem natus voluptas culpa velit autem in. Voluptate numquam tempora commodi sit rem consequatur debitis, eius facere cum non nesciunt architecto aperiam, molestias suscipit totam officiis ipsa libero eveniet fugit. Ipsa eaque atque quia rerum debitis dolore consectetur, saepe dolorem iste fugit incidunt error, doloremque temporibus? Dignissimos, laborum assumenda porro mollitia iure culpa. Dolor quod architecto a asperiores. Blanditiis sequi nesciunt ut velit recusandae, possimus ab quasi in quam sed quos voluptas perferendis! Ea nemo adipisci fugit, recusandae illo odio hic harum distinctio eligendi, voluptate quos alias reprehenderit sunt similique. Repellat, blanditiis minus voluptatum inventore accusantium quidem aliquid, ullam accusamus animi rerum distinctio laboriosam aliquam labore. Vel, modi est ad accusamus culpa voluptatem doloribus quo quaerat cum sint et voluptate qui atque, aut iste. Esse deserunt, incidunt aliquid atque exercitationem tempore facere, quos fugit, qui sapiente excepturi! Quisquam modi saepe ab reiciendis sit tempore eum vel harum nemo, deleniti fugit.</p>
        </div>
    );
};

export default About;